<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>xplore-worker-secrets</UserSecretsId>
	</PropertyGroup>



	<ItemGroup>
		<ProjectReference Include="..\Xplore.Application\Xplore.Application.csproj" />
		<ProjectReference Include="..\Xplore.Infrastructure\Xplore.Infrastructure.csproj" />
		<ProjectReference Include="..\Xplore.Contracts\Xplore.Contracts.csproj" />
		<ProjectReference Include="..\Xplore.ServiceDefaults\Xplore.ServiceDefaults.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Qdrant.Client" Version="9.1.0" />
		<PackageReference Include="MassTransit" Version="8.3.0" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
		<PackageReference Include="PdfPig" Version="0.1.9" />
		<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
	</ItemGroup>
</Project>
