namespace Xplore.Domain.Entities;

/// <summary>
/// Represents a chat interaction between a user and the AI assistant.
/// Used for analytics, history, and feedback tracking.
/// </summary>
public class ChatInteraction
{
    public Guid Id { get; set; }
    
    /// <summary>
    /// The museum context for this interaction (multi-tenancy).
    /// </summary>
    public Guid MuseumId { get; set; }
    
    /// <summary>
    /// Session ID to group related messages together.
    /// </summary>
    public Guid? SessionId { get; set; }
    
    /// <summary>
    /// The user's question.
    /// </summary>
    public required string UserQuestion { get; set; }
    
    /// <summary>
    /// The AI-generated response.
    /// </summary>
    public required string AiResponse { get; set; }
    
    /// <summary>
    /// Context chunks retrieved from Qdrant (for debugging/analytics).
    /// </summary>
    public string? RetrievedContext { get; set; }
    
    /// <summary>
    /// Whether the response was generated by AI or a fallback.
    /// </summary>
    public bool IsAiGenerated { get; set; }
    
    /// <summary>
    /// User feedback: true = positive, false = negative, null = no feedback.
    /// </summary>
    public bool? UserFeedback { get; set; }
    
    /// <summary>
    /// Estimated sentiment of the user's question (-1 to 1).
    /// </summary>
    public float? Sentiment { get; set; }
    
    /// <summary>
    /// Tags for topic categorization (e.g., "Logistics", "Art", "History").
    /// </summary>
    public string? Tags { get; set; }
    
    /// <summary>
    /// Tokens used for this interaction (for cost tracking).
    /// </summary>
    public int? TokensUsed { get; set; }
    
    /// <summary>
    /// Response time in milliseconds.
    /// </summary>
    public int? ResponseTimeMs { get; set; }
    
    /// <summary>
    /// When the interaction occurred.
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
