<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Xplore.Application\Xplore.Application.csproj" />
    <ProjectReference Include="..\Xplore.Domain\Xplore.Domain.csproj" />
  </ItemGroup>

  	<ItemGroup>
		<PackageReference Include="MassTransit" Version="8.3.0" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="8.3.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
		<PackageReference Include="Microsoft.SemanticKernel" Version="1.73.0" />
		<PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.73.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Qdrant.Client" Version="1.12.0" />
		<PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
	</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
